### ISSUE TITLE
Dark/black theme

### ISSUE THREAD

**Issue by anonymous-user** [Kennyc1012/OpenImgur#17]
I would like to see the app have a black theme. It would be useful for AMOLED displays as well as people who just like dark themes.

**Comment by Kennyc1012** [comment]
Is the Grey theme not dark enough?

**Comment by anonymous-user** [comment]
From what I see only the actionbar changes color not the app background, navigation drawer, or settings.

**Comment by Kennyc1012** [comment]
If you can point me towards an app or provide a screenshot that achieves this, it would be greatly appreciated.

**Comment by anonymous-user** [comment]
There are lots of apps with both light and dark themes: Reddit Sync, FeedlyReader, FX File Manager, Flud, etc.

**Comment by Kennyc1012** [comment]
Added in version 2.2

**Comment by anonymous-user** [comment]
Thank you very much. The new dark theme looks fantastic!
