### ISSUE TITLE
(Optional) More streamlined upload option

### ISSUE THREAD

**Issue by anonymous-user** [Kennyc1012/OpenImgur#18]
First OpenImgur opens, then you have to manually press Upload, and finally the app prompts you if you want to upload without logging in. I frequently upload screenshots I want to quickly post somewhere. It would be great if there was an option to skip the account prompt and another option to automatically upload. This way I can quickly upload and copy the link.

**Comment by Kennyc1012** [comment]
As a side note, you can share images through the share intent via Android/

**Comment by Kennyc1012** [comment]
b3721f89710e2826c0f8f2b2cc94116ad9d21d5f
