### ISSUE TITLE
Can't build, resources missing (app.*)

### ISSUE THREAD

**Issue by nilsbraden** [Kennyc1012/OpenImgur#26]
The following two lines for example in activity_view.xml seem to be making trouble:

    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:panelHeight="?android:attr/actionBarSize"

The folder app/ is displayed as empty by Android Studio and when I try to build I get the following error:

    /home/n/workspace/OpenImgur/src/main/res/layout/activity_view.xml
    Error:(1) No resource identifier found for attribute 'panelHeight' in package 'com.kennyc.open.imgur'
    Error:(1) No resource identifier found for attribute 'shadowHeight' in package 'com.kennyc.open.imgur'
    Error:(1) No resource identifier found for attribute 'dragView' in package 'com.kennyc.open.imgur'

Another issue is the integration of crashlytics which causes the build to fail if no API-Key is available. Since I don't want to use crashlytics for my own debug-builds I added the following flavor to the build.gradle (as suggested here: http://stackoverflow.com/questions/21894603/use-crashlytics-within-a-product-flavor-in-android-studio):

    productFlavors {
        noCrashlytics {
            ext.enableCrashlytics = false
        }
    }

Greetings,
Nils

**Comment by Kennyc1012** [comment]
That seems to be an issue with compiling the SlidingPanel library (compile 'com.sothree.slidinguppanel:library:+'). Can you post your gradle file.

**Comment by nilsbraden** [comment]
Ah right, that was the problem. Somehow Android Studio didn't lookup

    compile 'com.sothree.slidinguppanel:library:+'

but when I changed it to

    compile 'com.sothree.slidinguppanel:library:2.0.4'

it worked just fine. Strange.

Thank you for the quick reply though :)

**Comment by Kennyc1012** [comment]
Turns out the latest version of slidinguppanel changed the attribute names. Updated to the latest version and changed the attributes, everything works as expected.
