### ISSUE TITLE
Include redirect url in README

### ISSUE THREAD

**Issue by Jawnnypoo** [Kennyc1012/OpenImgur#39]
It would be great if you could include the redirect url that you are using in the app in the readme, in the section where it talks about generating an API key and secret. That way people would not have to go digging through the source to find the proper redirect url:

https://com.kenny.openimgur/

Just a though to save people time.

**Comment by Kennyc1012** [comment]
Submit a pull request and I'll accept it :P

**Comment by Jawnnypoo** [comment]
You beat me to it! Thanks :+1:
