### ISSUE TITLE
Fix gif loading and displaying

### ISSUE THREAD

**Issue by lhark** [Kennyc1012/OpenImgur#5]
When trying to play a gif by clicking on it, most of the time the app will respond by "unable to load gif". It seems to have to do with the loadAndDisplayGif() (though i only took a very short peak at the code) apparently it only can succeed if the gif is already cached. But unfortunatly, the UI does not provide any mean to know if this is the case.

**Comment by Kennyc1012** [comment]
Yes, in order for loadAndDisplayGif() to work, the gif has to be cached, but there is a check before that is called. 

https://github.com/Kennyc1012/OpenImgur/blob/master/src/main/java/com/kenny/openimgur/fragments/ImgurViewFragment.java#L309

If the file does not exist, it will be downloaded, then after it is downloaded, displayed. If you can send me a link to the images that are not working (the share button in the action bar will export the link), I can take a look at them, or if you are able to run a debug build, copy and paste the logs.

**Comment by lhark** [comment]
So first time after launching the app, when it happens i get an error message titled : "An unexpected error has occured. Please try again.", Saying : "Unable to load image." with a single cancel button.
First URL :http://imgur.com/gallery/hl24UOT
The for all the other gifs that refuse to load, i only get the "Unable to load image." message at the bottom of the screen.
URLs : 
* http://imgur.com/gallery/2qW49aO
* http://imgur.com/gallery/zKscFP8
* http://imgur.com/gallery/P5BASEm

Each time the error message is instant, no time spent trying to load something.
However gifs that have successfully been loaded before and are now in cache load without problem

**Comment by Kennyc1012** [comment]
All of those links work fine for me on several different devices (Nexus 5/6/7, One+1). However, it appear they are all gifv(mp4) images, which could possibly be the reason (not exactly sure why though). Try clearing the image cache from the settings Menu (From the nav drawer Settings -> Cache -> Current Cache Size -> Yes. 

If this doesn't work, uninstall/reinstall the app might clear it up. 

Also, can you list details about the device you are using, Model, Android version, Amount of space left on device etc...

**Comment by lhark** [comment]
* Model : Sony Ericsson Xperia Ray ST18i
* Android 4.0.4
* Kernel 2.6.32.9-perf
* Build 4.1.B.0.587 (it's rooted)
* external storage : 32Go, 50% left
* internal storage : 400Mo , 40Mo left

I already deleted the cache once but that didn't help. I could try again though.
My advice, when dealing with such amount of data, would be to use external storage.
People with low internal storage capacity would thank you :)

I will try to reinstall and see if that fixes it.

**Comment by Kennyc1012** [comment]
I would say that the culprit is that there is not enough internal storage left and it failed immediately, as that is where the the caches are saved to. If you can, delete unused apps and/or their caches, that should help. I will work in an option to have the cache save on the external partition in a future build.

**Comment by lhark** [comment]
I'm not so sure about that, i retested and i got most of the gifs to load appart from the ones that already didn't want to load. When they failed i had over 40Mo left (40Mo is the warning threshold), and i had other gifs loading correctly after that. 
For example this one loaded : http://imgur.com/gallery/Y76QptF (30Mo left)

**Comment by Kennyc1012** [comment]
a490286a3fb57d2847e2ed9c2752f8b2d8a43e5f
