### ISSUE TITLE
Enhancement: Gallery Search

### ISSUE THREAD

**Issue by Jawnnypoo** [Kennyc1012/OpenImgur#51]
Seems like when comparing this app with the official one, this is one of the only features that this app truely lacks. Would love to help out on this if you want.

**Comment by Kennyc1012** [comment]
I'm unsure of the architecture on this. I don't want to create a new fragment from the nav drawer for search, but I don't want it contained in another fragment either.

**Comment by Jawnnypoo** [comment]
I assumed it would work similarly to how search works in Google Play. You have a search icon at the top of the Gallery fragment, and when you search, it opens the results in a new fragment that is a list of the results, with a back arrow in the toolbar. So, the search results are not really a screen that you can navigate to, rather a reactionary screen. This is basically the way the search gallery feature works in the official app, but I believe it is better, since it allows the user to see the search without opening the nav drawer, and we could include the search icon in the toolbar on the results screen as well, so that the user could easily search again, as they have it function in Google Play.

Thoughts?

**Comment by Kennyc1012** [comment]
Seems reasonable enough. I think instead of popping a fragment on top of MainActivity (or replacing the current one) it should open up into a new activity kind of what the Google+ app does.

**Comment by Jawnnypoo** [comment]
I see. So Play and Plus do it two different ways, where as soon as you tap the search, it opens the new activity (Plus) vs waiting till you hit enter on the query to open the new activity (Play). Either way, the new activity allows for additional searches, which keep you in that same "SearchResultsActivity"

**Comment by Kennyc1012** [comment]
I think it should be a mixture of both. Have a search view in the GalleryFragment, then when you hit submit, it will take you to the search activity which will display the results and allow you to continue to search if you want.

**Comment by Kennyc1012** [comment]
The [gallery_search](https://github.com/Kennyc1012/OpenImgur/tree/gallery_search) brach has been created for this. All work regarding search should be pushed there.
