### ISSUE TITLE
Background Uploads

### ISSUE THREAD

**Issue by Kennyc1012** [Kennyc1012/OpenImgur#53]
Allow uploads to occur in the background and display a notification upon success/failure. The notification should allow the user to retry the upload if it failed, or copy the link if successful.

**Comment by Jawnnypoo** [comment]
To tack on to this, when the user downloads an image, they can potentially receive a failed notification, which should probably also be click to retry.

**Comment by Kennyc1012** [comment]
@Jawnnypoo That will be broken out into a separate ticket.

**Comment by towolf** [comment]
Hey, I just received your most recent update to Open Imgur. 

It’s nice that you added the »background uploading« feature. Thanks for that.

How I imagined it was that when using using »Share« from an app, it would not pop up the dialog with options, but go straight to background upload and make the notification when finished. This would facilitate quickly going through a list of images and to post them, either on Reddit or in a chat.

I guess the regular »Share« action should be the dialog, but I wonder if a second action can be added that skips that.

**Comment by towolf** [comment]
Also, tapping on the upper part of the notification does nothing. On the (defunct) *Imgur Holo* this opened the URL in the browser (or whatever was associated with the URL) and the lower part copied to clipboard.

**Comment by Kennyc1012** [comment]
There is currently no support action for tapping the upper part of the notification so that is as expected. Opening it up in a browser, I feel, would be redundant as you know what the image is since you just uploaded it >_>

As for the uploading still requiring some input, this will always remain as some people will want to add a title and/or description. Creating two different ways of uploading isn't worth the work/effort if the other option is pressing an additional button.

**Comment by towolf** [comment]
Opening the URL in browser is not so important. But it makes sense in the context of the usage scenario I had in mind.

Say you want to tell someone a picture illustrated story (in Reddit, or in a chat). You are in your gallery app and need to upload and get URLs for 10 pictures.

It would be slow to switch to the other app (the dialog) for each one. And there’s cases where I don’t want to make an album, or add titles or description. I’m merely after a bunch http://i.imgur.com/foobar.jpg URL: Pick image, share, pick another, share, etc.

If »Share« just silently takes care of that I can later refer to the list of notifications and grab the URL from each one as needed.

And the browser thing would help to make sure the link works, and toverify which image it is.

**Comment by Kennyc1012** [comment]
The scenario sounds plausible, but for the time being, it will function as is. This might be revisited in the future.
