### ISSUE TITLE
Enhancement: Use Gfycat

### ISSUE THREAD

**Issue by Jawnnypoo** [Kennyc1012/OpenImgur#57]
Gfycat converts gifs to a much more compressed HTML5 video format. Gfycat allows conversion programatically, and it also allows you to make an API call to check and see if a link has already been converted on Gyfcat.

https://gfycat.com/api

 Many Imgur/Reddit apps use this already to speed up load times and reduce bandwidth. It would be a worthwhile thing to look into integrating to speed up the app overall.

**Comment by Kennyc1012** [comment]
Messing around with it real quick, I don't see anything beneficial. The converted gif is still the same size (1.5mb) and the mp4 video is actually larger (2.7mb vs 2.1mb). Granted these were the first gifs/mp4s I came across. 

![screen shot 2015-03-24 at 8 23 32 pm](https://cloud.githubusercontent.com/assets/2333025/6816000/b3e4de62-d263-11e4-920f-a37fef44855f.png)

**Comment by Jawnnypoo** [comment]
I checked on some of the top gifs on /r/gif today, and here are some of the results:

https://gfycat.com/FeistyGiganticGiantschnauzer 
From 7mb to 3mb

https://gfycat.com/RepulsiveBlissfulCatfish
99k to 33k

I believe you are correct though, it does only really make a difference if the images are .gif, and would not be worthwhile for .mp4 or .gifv. So, possibly have a check on the file extension and only bother checking for a gfycat link if it is relevant.

**Comment by Kennyc1012** [comment]
If that's the case, than I rather just use the mp4 links for .gifs and avoid this all together. Right now the limit to load a gif is 5mb, I can lower it, or have a setting where the user can select the maximum gif size.
