### ISSUE TITLE
Swiping between paginated images does not work

### ISSUE THREAD

**Issue by The-Compiler** [Kennyc1012/OpenImgur#58]
It seems OpenImgur "paginates" images, i.e. if I scroll down to the bottom, another set of images gets loaded.

When swiping from image to image however, when I'm at the last image of a page, I can't swipe right to the next image - instead I have to go back to the gallery view and load the new page.

Also, thanks for your work! Definitely more happy with this than with the official Imgur app :)

/cc @seir-

**Comment by Kennyc1012** [comment]
This is as intended. Having large amounts of images to swipe between can lead to memory issues and crashes. This can be seen on the Imgur website and the app. After swiping between images for a while, the site becomes slow and unresponsive and images fail to load.
