### ISSUE TITLE
Add Experimental Settings Section

### ISSUE THREAD

**Issue by psykzz** [Kennyc1012/OpenImgur#63]
When loading a few images on a slow connection, they all show loading and all complete in one go, as if they were all scheduled at the same time.

I find that if i continue to view new images they all get added and none will show until the last image has loaded.

**Comment by Kennyc1012** [comment]
The Maximum number of threads that can be spawned for loading images is 5 seen [here](https://github.com/Kennyc1012/OpenImgur/blob/master/src/main/java/com/kenny/openimgur/util/ImageUtil.java#L165). So when loading several images, the new ones won't start loading until the other ones finishes or get canceled. This number can be increased but at the risk of causing memory issues.

**Comment by psykzz** [comment]
I typically use the app over LTE or Wifi,
Would you be okay with having a setting to increase the number.

I can report back after a week or so with what i think is a good alternative

**Comment by Kennyc1012** [comment]
I can provide you with an APK that has that number increased and you can see its performance. Just a couple questions:

1. What device are you using and what are its specs, IE ram, CPU, storage, OS version etc...
 
2. What limit would you like it to be set to? I would suggest nothing higher than 10 as I feel that may be unstable, but the call is up to you.

If all seems well, I can work in an "Experimental" section under settings that can allow for the tweaking of such settings.

**Comment by psykzz** [comment]
With the APK Sure that sounds fine.

My device is a Oneplus One. Think Nexus 5 with a little better specs.
Try around 10, if you think thats a good starting point.

**Comment by Kennyc1012** [comment]
Okay, I plan making a new release today, so I will make yours based off of that with the upped number. I should have to done within a few hours.

**Comment by Kennyc1012** [comment]
[Here](https://drive.google.com/file/d/0B76YfpA-PixvQjVoR2M0b2tWYUU/view?usp=sharing) is the link to the APK as promised. It is the same as the 2.5 release except it has a limit of 10 threads.

**Comment by psykzz** [comment]
Just initially testing this out and its working perfectly. Will continue to give feedback throughout the week.

**Comment by psykzz** [comment]
So two weeks passed and I notice the app updating so I'm guessing changes lost. With the increased limit I found it perfectly reasonable.

**Comment by Kennyc1012** [comment]
I'll work in an experimental settings area in a future release that will allow for this to change.
