### ISSUE TITLE
Can't login via 3rd party accounts

### ISSUE THREAD

**Issue by ataulm** [Kennyc1012/OpenImgur#7]
- Open nav drawer
- Click login
- select twitter

- expected: twitter oauth page should appear
- actual: twitter element highlighted but no page opened

**Comment by Kennyc1012** [comment]
This is an issue with Imgurs login page, until it is fixed on there end there is nothing that can be done.

**Comment by ataulm** [comment]
Duplicate of #1. Tried logging out of official Imgur app and logging back in via Twitter, it opens the Twitter auth page in a new window (opens in chrome)
